<h1>Dodaj artykuł</h1>
<?php $this->getMessage(); ?>

<form method="post">
	<table> 
	   <tbody>
	   	  <td>Tytuł</td>
	           <td>
	               <textarea name="tytul" cols="20" rows="1"></textarea>
	           </td>
	       <tr>
	      <td>Treść</td>
	           <td>
				<textarea name="tresc" cols="70" rows="5"></textarea>
	           </td>
	       </tr>		  		  
		  <tr>	  
		  <td colspan="2" style="text-align: center">			 
				 <tr><td colspan=2 style="text-align:center;"> <button class="button" name="dodaj">Dodaj artykuł</button> </td></tr>          
			  </td>
		  </tr>
	  </tbody>
	</table>
</form>