<?php $this->getMessage(); ?>
<h1 style="margin: 20px 0px 40px 10px;">Dodaj artykuł</h1>

<form method="post">
	<center>
		<table style="width:900px;"> 
		   <tbody>
			  <td>Tytuł: </td>
				   <td>
					   <input style="width:900px;" type="text" name="tytul"/>
				   </td>
			   <tr>
			  <td>Treść: </td>
				   <td>
				<p>
					<div id="editControls">
						<div>
							<a data-role="undo" href="javascript:void(0)"><i class="fa fa-undo"></i></a>
							<a data-role="redo" href="javascript:void(0)"><i class="fa fa-repeat"></i></a>
							<a data-role="bold" href="javascript:void(0)"><i class="fa fa-bold"></i></a>
							<a data-role="italic" href="javascript:void(0)"><i class="fa fa-italic"></i></a>
							<a data-role="underline" href="javascript:void(0)"><i class="fa fa-underline"></i></a>
							<a data-role="strikeThrough" href="javascript:void(0)"><i class="fa fa-strikethrough"></i></a>
							<a data-role="justifyLeft" href="javascript:void(0)"><i class="fa fa-align-left"></i></a>
							<a data-role="justifyCenter" href="javascript:void(0)"><i class="fa fa-align-center"></i></a>
							<a data-role="justifyRight" href="javascript:void(0)"><i class="fa fa-align-right"></i></a>
							<a data-role="justifyFull" href="javascript:void(0)"><i class="fa fa-align-justify"></i></a>
							<a data-role="indent" href="javascript:void(0)"><i class="fa fa-indent"></i></a>
							<a data-role="outdent" href="javascript:void(0)"><i class="fa fa-outdent"></i></a>
							<a data-role="insertUnorderedList" href="javascript:void(0)"><i class="fa fa-list-ul"></i></a>
							<a data-role="insertOrderedList" href="javascript:void(0)"><i class="fa fa-list-ol"></i></a>
							<a data-role="h1" href="javascript:void(0)">h<sup>1</sup></a>
							<a data-role="h2" href="javascript:void(0)">h<sup>2</sup></a>
							<a data-role="p" href="javascript:void(0)">p</a>
							<a data-role="subscript" href="javascript:void(0)"><i class="fa fa-subscript"></i></a>
							<a data-role="superscript" href="javascript:void(0)"><i class="fa fa-superscript"></i></a>
						</div>
					</div>
					<div id="editor" contenteditable=""></div>
					<textarea id="output" name="tresc" style="width:100%;height:400px;display:none;"></textarea>
				</p>
				   </td>
			   </tr>		  		  
			  <tr>	  
			  <td colspan="2" style="text-align: center">			 
					 <tr><td colspan=2 style="text-align:center;"> <button class="button" name="dodaj">Dodaj artykuł</button> </td></tr>          
				  </td>
			  </tr>
		  </tbody>
		</table>
	</center>
</form>