<?php $this->getMessage(); ?>
<h1>Artykuły</h1>

<form action="index.php?con=artykuly" method="post">
	<table id="styled">
	<thead>
		<tr>
			<th>Tytuł</th>
			<th>Ocena</th>
			<th>Wyświetl recenzje</th>
			<th>Oceń artykuł</th>
		</tr>
	</thead>
	<tbody>
		<?php if (!$artykuly): ?>
			<tr>
				<td colspan="5" style="text-align: center">
					Brak dodanych artykułów
				</td>
			</tr>
		<?php else: ?>
		<?php foreach ($artykuly as $artykul): ?>
			<tr>
				<td> <?php echo $artykul['Tytul'] ?> </td>
				<td> <?php echo $artykul['Ocena'] ?> </td>
				<td> 
					<?php if (!$artykul['Tresc']): ?>
					<?php else: ?> 
						<button class="button" value="<?php echo($artykul['ID_Recenzja']); ?>" name="recenzja">Recenzja </button> 
					<?php endif ?> 
				</td>
				<td> <?php if ($artykul['Tresc']): ?>
				<?php else: ?> <button class="button" value="<?php echo($artykul['ID_Artykul']); ?>" name = "ocena">Oceń</button> <?php endif ?> </td>
			</tr>
		<?php endforeach ?>
		<?php endif ?>
	</tbody>
		<tr>
			<td></td>
			<td>
				<input type="number" min="-5" max="5" STYLE="width:200px; height: 20px" name="grupujoceny"><br><br>
				<button class="button" name="grupuj2">Grupuj</button>
			</td>
			<td></td>
			<td></td>
		</tr>
	</table>
	</form>



