<?php $this->getMessage(); ?>
<h1>Artykuły</h1>

<form action="index.php?con=artykuly" method="post">
	<table id="styled">
	<thead>
		<tr>
			<th>Tytuł</th>
			<th>Recenzje</th>
		</tr>
	</thead>
	<tbody>
		<?php if (!$artykuly): ?>
			<tr>
				<td colspan="5" style="text-align: center">
					Brak dodanych artykułów
				</td>
			</tr>
		<?php else: ?>
		
		<?php foreach ($artykuly as $artykul): ?>
			<tr>
				<td>  <input type="hidden" value="<?php echo($artykul['ID_Artykul']); ?>" name="qwe"><?php echo $artykul['Tytul'] ?> </td>
				<td> 
					<a href="index.php?con=artykuly_recenzje&id=<?php echo($artykul['ID_Artykul']); ?>" class="button">Wyświetl</a> 
					
			</tr>
		<?php endforeach ?>
		
		<?php endif ?>
	</tbody>
	</table>
	</form>

</br>
<div style="float:right">
	<a href="index.php?con=konferencja&act=load&id=<?php echo($_SESSION['id_konf']); ?>" class="button">Wróć</a>
</div>
<div style="clear:both;"></div>