<center><h1>Przeglądaj zdarzenia </h1></center>

<?php $this->getMessage(); ?>
		
		


	<form method="post" id ="formularz">
		<center><table> 
		<tr><td> Zaznacz według jakich kryteriów chcesz pokazać zdarzenia dotyczace konferencji : </td></tr>
		<tr><td> Wybierz zdarzenie od: </td><td> <input type="date" name ="data_od"></td></tr>
		<tr><td> Wybierz zdarzenie do :</td><td> <input type="date" name ="data_do"></td></tr>
		<tr><td> Wybierz minimalny limit miejsc:</td><td> <input type="text" name ="limit_miejsc"></td></tr>

		
		<tr><td> Zaznacz według jakich kryteriów chcesz pokazać zdarzenia dotyczace recenzji : </td></tr>
		<tr><td> Wybierz zdarzenie od: </td><td> <input type="date" name ="data_od_recenzji"></td></tr>
		<tr><td> Wybierz zdarzenie do :</td><td> <input type="date" name ="data_do_recenzji"></td></tr>
		<tr><td colspan=2 style="text-align:center;"> <button name="szukaj">Szukaj</button> </td></tr>
		</table></center>
	</form>
	

