<h1>Edytuj profil</h1>

<?php $this->getMessage(); ?>

	<form method="post">
		<table> 
		<tr><td> Imię: </td><td> <input type="text" name="imie"></td></tr>
		<tr><td> Nazwisko: </td><td> <input type="text" name="nazwisko"></td></tr>
		<tr><td> Email: </td><td> <input type="text" name="email"></td></tr>
		<tr><td> Nr telefonu: </td><td> <input type="text" name="nr_telefonu"></td></tr>
		<tr><td colspan=2 style="text-align:center;"> <button name="akceptuj">Zapisz zmiany</button> </td></tr>
		</table>
	</form>