<?php $this->getMessage(); ?>
<h1>Edytuj profil</h1>
	<form method="post">
		<table> 
		<tr><td> Imię: </td><td> <input type="text" name="imie"></td></tr>
		<tr><td> Nazwisko: </td><td> <input type="text" name="nazwisko"></td></tr>
		<tr><td> Email: </td><td> <input type="text" name="email"></td></tr>
		<tr><td> Nr telefonu: </td><td> <input type="text" name="nr_telefonu"></td></tr>
		<tr><td colspan=2 style="text-align:center;"> <button class="button" name="akceptuj">Zapisz zmiany</button> </td></tr>
		</table>
	</form>