	</div>

	<footer>© 2015 “E-Konferencja”. Stworzone przez grupę L08-02.</footer>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
	<script src="http://sharpik.com/wip/cuteselect/cuteselect.min.js"></script>
	<script src='http://tablesorter.com/__jquery.tablesorter.min.js'></script>
	<script>
		$('#editControls a').click(function (e) {
			switch ($(this).data('role')) {
			case 'h1':
			case 'h2':
			case 'p':
				document.execCommand('formatBlock', false, $(this).data('role'));
				break;
			default:
				document.execCommand($(this).data('role'), false, null);
				break;
			}
			update_output();
		});

		$('#editor').bind('blur keyup paste copy cut mouseup', function (e) { update_output(); });

		function update_output() { $('#output').val($('#editor').html()); }
		
		$(function () { $('#styled').tablesorter(); });
	</script>
</body>
</html>