<!DOCTYPE html>
<html class="">
<head>
	<meta charset="UTF-8" />
	<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
	<link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<body>
	<div id="logo"></div>
	<div id="container">
		<div id="menu">
		  <ul class="nav">
			 <li class="active"><a href="index.html">Strona główna</a></li>
			 <li class="has-sub"><a href="#">Konferencje</a>
				<ul class="left">
				   <li><a href="#">Kategoria 1</a></li>
				   <li><a href="#">Kategoria 2</a></li>
				</ul>
			 </li>
			 <li><a href="#">Pomoc</a></li>
			 <li><a href="#">Kontakt</a></li>
		  </ul>
		  <ul class="login">
			<li class="visit"><a href="index.html">Rejestracja</a></li>
			<li class="visit has-sub"><a href="index.html"><img class="frame" height="20" src="http://img1.wikia.nocookie.net/__cb20091231054441/splintercell/images/3/39/Unknown_male.jpg"> Zaloguj się</a>
				<ul class="right">
					<li><a href="#">Mój profil</a></li>
					<li><a href="#">Wyloguj</a></li>
				</ul>
			</li>
		  </ul>
		</div>
	<div id="findit">
	<h1>Znajdź konferencję dla siebie</h1>
	</div>