<!DOCTYPE html>
<html class="">
<head>
	<meta charset="UTF-8" />
	<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
	<link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<body>
	<a href="index.php" id="logo"></a>
	<div id="container">
		<div id="menu">
		  <ul class="nav">
			 <li class="active"><a href="index.php">Strona główna</a></li>
			 <li class="has-sub"><a href="#">Konferencje</a>
				<ul class="left">
				   <li><a href="index.php?con=tworzeniekonferencji">Dodaj konferencje</a></li>
				   <li><a href="index.php?con=zarz_artykulami">Zarządzaj artykułami</a></li>
				   <?php if($this->isLogged()) { ?><li><a href="index.php?con=art_do_publikacji">Wybierz artykuły do publikacji</a></li> <?php }?>
				</ul>
			 </li>
			 <li><a href="#">Pomoc</a></li>
			 <li><a href="#">Kontakt</a></li>
		  </ul>
		  <ul class="login">
		  <?php if(!$this->isLogged()) { ?>
			<li class="visit"><a href="index.php?con=rejestracja">Rejestracja</a></li>
			<li class="visit"><a href="index.php?con=login"><img class="frame" height="20" src="http://img1.wikia.nocookie.net/__cb20091231054441/splintercell/images/3/39/Unknown_male.jpg"> Zaloguj się</a></li>
		  <?php } else { ?>
			<li class="visit has-sub"><a><img class="frame" height="20" src="http://img1.wikia.nocookie.net/__cb20091231054441/splintercell/images/3/39/Unknown_male.jpg"> Mój profil</a>
				<ul class="right">
					<li><a href="index.php?con=edycjaProfilu">Edytuj profil</a></li>
					<li><a href="index.php?con=zmienHaslo">Zmień hasło</a></li>
					<?php if($this->isAdmin()) { ?>
						<li><a href="index.php?con=dziennikZdarzen">Dziennik zdarzeń</a></li>
						<li><a href="index.php?con=dodajAdministratora">Dodaj administratora</a></li>
					<?php } ?>
					<li><a href="index.php?con=login&act=logout">Wyloguj</a></li>
				</ul>
			</li>
		  <?php } ?>
		  </ul>
		</div>
