<?php $this->getMessage(); ?>

<h2 style="margin:30px 0px 0px 20px;">Przegląd konferencji</h2>

<?php if($this->konferencja) { ?>
	<div class="post entry" style="width:100%; margin:30px 0px 20px 0px;">
		<div class="hexagon"><a href="#"><i class="fa fa-book"></i></a></div>
		<div class="post-image">
			<figure>
				<div class="imgcon full">
					<?php echo($this->konferencja['Nazwa']); ?>
				</div>
			</figure>
		</div>
		<div class="post_content">
			<h2>Dane:</h2> 
			<div class="border"></div>
			<p>
				<table style="width:425px;">
					<tr><td><b>Data konferencji: </b></td><td><?php echo($this->konferencja['Data']); ?></td></tr>
					<tr><td><b>Miejsce: </b></td><td><?php echo($this->konferencja['Miejsce']); ?></td></tr>
					<tr><td><b>Wolnych miejsc: </b></td><td><?php echo($this->konferencja['Limit_Miejsc']-$this->konferencja['Ilosc_uczestnikow']); ?> <b>na</b> <?php echo($this->konferencja['Limit_Miejsc']); ?></td></tr>
					<tr><td><b>Termin zgłoszeń: </b></td><td><?php echo($this->konferencja['Termin_Zgloszen']); ?></td></tr>
					<?php if((int)$this->konferencja['Koszt'] > 0) { ?>
						<tr><td><b>Koszt: </b></td><td><?php echo($this->konferencja['Koszt']); ?></td></tr>
					<?php } else { ?>
						<tr><td><b>Koszt: </b></td><td>wstęp wolny</td></tr>
					<?php } ?>
					
					<?php if((int)$this->konferencja['Ilosc_Ocen'] > 0) { ?>
						
							<tr><td><b>Ocena: </b></td><td><?php echo($this->konferencja['Suma_Ocen']/$this->konferencja['Ilosc_Ocen']); ?></td></tr>
					
					<?php } else { ?>
						<tr><td><b>Ocena: </b></td><td>brak</td></tr>
					<?php } 
					$dzisiaj=date("Y-m-d H:m:s");
					 if($this->isUczestnik_accepted($_GET['id']) AND ($dzisiaj > $this->konferencja['Data']))
					{{ ?>
							<tr><td><b>Oceń (od-5 do 5): </b></td>
							<td>
								<form action="index.php?con=ocenaKonferencji&id=<?php echo($_GET['id']); ?>" method="post">
									<input type="number" name="ocena" min="-5" max="5" style="width: 40px;">
									<input style="button" type="submit" value="Oceń" name="ocen">
								</form>
							</td></tr>
						<?php } ?>
					<?php } ?>
				</table> 
			</p>
			<hr>
			<h2>Program konferencji:</h2>
			<div class="border"></div>
			<p><?php echo($this->konferencja['Program']); ?></p>
			<hr>
		</div>
		<div class="post-footer">
			<div class="post-footer-line">
				<span><i class="fa fa-user"></i> 
					<?php foreach($this->konferencja['Organizatorzy'] as $o) echo($o['Imie'].' '.$o['Nazwisko'].', '); ?>
				</span><br>
				<?php if((int)$this->konferencja['Ilosc_artykulow'] > 0) { ?>
					<?php if($this->isLogged()): ?>
						<?php if($this->isAdmin() || $this->isOrganizatorKonferencji($_GET['id']) || $this->isRecenzent()):?>
						<span><i class="fa fa-comment"></i> <a href="index.php?con=artykuly&act=edit&id=<?php echo($_GET['id']); ?>"><?php echo($this->konferencja['Ilosc_artykulow']); ?> artykułów</a></span><br>
						<?php else:?>
						<span><i class="fa fa-comment"></i> <?php echo($this->konferencja['Ilosc_artykulow']); ?> artykułów</span><br>
						<?php endif ?>
					<?php else:?>
						<span><i class="fa fa-comment"></i> <?php echo($this->konferencja['Ilosc_artykulow']); ?> artykułów</span><br>
					<?php endif ?>
				<?php } else { ?>
					<span><i class="fa fa-comment"></i> brak artykułów</span><br>
				<?php } ?>
				<span><i class="fa fa-tag"></i> <?php echo(($this->konferencja['Temat'])?'<a href="#">'.$this->konferencja['Temat'].'</a>':'brak tematu'); ?></span>
			</div>
		</div>
	</div>
	<div style="clear:both;"></div>
	<div style="float:right">
	
		<?php if($this->isLogged()) { ?>
		
			<?php if($this->isAdmin() || $this->isOrganizatorKonferencji($_GET['id']) || $this->isRecenzent()) { ?>
			
				<?php if((int)$this->konferencja['Ilosc_artykulow'] > 0) { ?>
					<a href="index.php?con=artykuly&id_konferencji=<?php echo($_GET['id']); ?>" class="button">Wyświetl artykuły</a>
				<?php } ?>
				
				<?php if($this->isAdmin() || $this->isOrganizator()) { ?>
					<a href="index.php?con=art_dodaj&id_konferencji=<?php echo($_GET['id']); ?>" class="button">Dodaj artykuł</a>
				<?php } ?>
				
			<?php } ?>
			
			<?php if(!$this->isOrganizatorKonferencji($_GET['id']) && ($this->konferencja['Limit_Miejsc']-$this->konferencja['Ilosc_uczestnikow']) > 0 && !$this->isUczestnik($_GET['id'])) { ?>
				<a href="index.php?con=konferencja&act=add&id=<?php echo($_GET['id']); ?>" class="button">Dołącz do konferencji</a>
			<?php } ?>
			
			<?php if($this->isAdmin() || $this->isOrganizatorKonferencji($_GET['id'])) { ?>
				<a href="index.php?con=konferencja&act=edit&id=<?php echo($_GET['id']); ?>" class="button">Edytuj konferencję</a> <a href="index.php?con=konferencja&act=delete&id=<?php echo($_GET['id']); ?>" class="button">Usuń konferencję</a>
			<?php } ?>

		<?php } ?>
	</div>
	<div style="clear:both;"></div>
<?php } ?>
