<h1>Zgłoś temat konferencji</h1>
<?php $this->getMessage(); ?>
<form method="post">
    <table border="0" style="width: 350px">
    	<tbody>
    		<tr>
    		  <td>Temat:</td>
    		  <td>
    		      <input type="text" name="temat" maxlength="30" style="width: 100%" />
    		  </td>
    		</tr>
    		<tr>
    		  <td colspan="2">
    		      <input type="submit" name="submit" value="Dodaj" />
    		  </td>
    		</tr>
    	</tbody>
    </table>
</form>