<?php $this->getMessage(); ?>
<center><h1>Kontakt:</h1></center>
	<form method="post">
		<center>
		<tr><td><h3><font face="'Times New Roman'"> E-konferencja Sp.z o.o </h3></face></td><td>
		<tr><td><font face="'Times New Roman'">  Rzeszów, ul.Wincentego Pola  </td><td>
		<tr><td><h3><font face="'Times New Roman'"><br> Masz pytania? - Napisz do nas:  </h3></td><td>
		<tr><td><font face="'Times New Roman'"> E-mail: e-konferencja@wp.pl </td><td>
		<tr><td><font face="'Times New Roman'"><br> Lub zadzwoń: </td><td>
		<tr><td><font face="'Times New Roman'"><br> Nr. telefonu: 17555111 </td><td>
		
	</center>
	</form>