	<div id="findit">
		<h1>Znajdź konferencję dla siebie</h1>
		<form action="index.php?con=szukaj" method="post">
			<input type="text" placeholder="Podaj nazwę konferencji.." STYLE="width:350px; height: 20px" name="szukane"><br><br>
			<input type="submit" class="button" value="Szukaj" name="szukaj" STYLE="width:200px;">
		</form>
		</div>
		
		<?php $this->getMessage(); ?>
		<h2 class="h2-space" style="margin:20px 0px 0px 10px;">Ostatnio dodane konferencje:</h2>
		
		<?php foreach($result as $r): ?>
		<div class="post entry">
			<div class="hexagon"><a href="#"><i class="fa fa-book"></i></a></div>
			<div class="post-image">
			<figure class="effect">
				<a href="#"><img class="imgcon" src="images/konferencja.jpg" height="233px"></a>
				<figcaption>
					<div class="icons">
						<!--<i class="fa fa-facebook rounded"></i>
						<i class="fa fa-twitter rounded"></i>-->
					</div>
				</figcaption>
			</figure>
			</div>
			<div class="post_content">
				<h2><a href="#"><?php echo($r['Nazwa']); ?></a></h2>
				<div class="border"></div>
				<p> <?php echo(substr($r['Program'], 0, 70)."<br>..."); ?> </p>
				<a href="index.php?con=konferencja&id=<?php echo($r['ID_Konferencja']); ?>" class="button">Sprawdź</a>
				<hr>
			</div>
		</div>
		<?php endforeach ?>
		
		<div style="clear:both;"></div>