	<div id="findit">
		<h1>Znajdź konferencję dla siebie</h1>
		<form action="index.php?con=szukaj" method="post">
			<input type="text" placeholder="Podaj nazwę konferencji.." STYLE="width:350px; height: 20px" name="szukane"><br><br>
			<input type="submit" class="button" value="Szukaj" name="szukaj" STYLE="width:200px;">
		</form>
		</div>
		
		<?php $this->getMessage(); ?>
		<h3>Strona główna<h3>
		
		<h2 class="h2-space">Ostatnio dodane:</h2>
		<div class="post entry">
			<div class="hexagon"><a href="#"><i class="fa fa-book"></i></a></div>
			<div class="post-image">
			<figure class="effect">
				<a href="#"><img class="imgcon" src="images/konferencja.jpg" height="233px"></a>
				<figcaption>
					<div class="icons">
						<!--<i class="fa fa-facebook rounded"></i>
						<i class="fa fa-twitter rounded"></i>-->
					</div>
				</figcaption>
			</figure>
			</div>
			<div class="post_content">
				<h2><a href="#">Nazwa konferencji</a></h2>
				<div class="border"></div>
				<p> Krótki opis danej konferencji, program.</p>
				<a href="#" class="button">Sprawdź</a>
				<hr>
			</div>
			<div class="post-footer">
				<div class="post-footer-line">
					<span><i class="fa fa-user"></i><a href="#">Autor</a></span><br>
					<span><i class="fa fa-calendar"></i><a href="#">Poniedziałek, 16 luty 2015</a></span><br>
					<span><i class="fa fa-comment"></i><a href="#">9 recenzji</a></span><br>
					<span><i class="fa fa-tag"></i><a href="#">Temat</a></span>
				</div>
			</div>
		</div>
		
		<div style="clear:both;"></div>