<?php $this->getMessage(); ?>
<h1>Oceń artykuł</h1>

	<form method="post">
		<table> 
		<input type="hidden" name="id" value="<?php echo($_POST['ocena']); ?>"/>
		<tr><td> Podaj Ocene </td><td> <input type="text" name="ocena_"></td></tr>
		<tr><td> Wpisz recenzje </td><td> <textarea name="recenzja" cols="60" rows="20" ></textarea></td></tr>
		<tr><td colspan=2 style="text-align:center;"> <button name="zapiszocene">Zapisz recenzje</button> </td></tr>
		</table>
	</form>