<?php $this->getMessage(); ?>
<h1>Oceń artykuł</h1>

	<form action="index.php?con=artykuly" method="post">
		<table> 
			<input type="hidden" name="id" value="<?php echo($_POST['ocena']); ?>"/>
			<tr><td> Podaj ocenę </td><td> <input type="number" min="-5" max="5" name="ocena_"></td></tr>
			<tr><td> Wpisz recenzje </td>
				<td> <br>
					<div id="editControls">
						<div>
							<a data-role="undo" href="javascript:void(0)"><i class="fa fa-undo"></i></a>
							<a data-role="redo" href="javascript:void(0)"><i class="fa fa-repeat"></i></a>
							<a data-role="bold" href="javascript:void(0)"><i class="fa fa-bold"></i></a>
							<a data-role="italic" href="javascript:void(0)"><i class="fa fa-italic"></i></a>
							<a data-role="underline" href="javascript:void(0)"><i class="fa fa-underline"></i></a>
							<a data-role="strikeThrough" href="javascript:void(0)"><i class="fa fa-strikethrough"></i></a>
							<a data-role="justifyLeft" href="javascript:void(0)"><i class="fa fa-align-left"></i></a>
							<a data-role="justifyCenter" href="javascript:void(0)"><i class="fa fa-align-center"></i></a>
							<a data-role="justifyRight" href="javascript:void(0)"><i class="fa fa-align-right"></i></a>
							<a data-role="justifyFull" href="javascript:void(0)"><i class="fa fa-align-justify"></i></a>
							<a data-role="indent" href="javascript:void(0)"><i class="fa fa-indent"></i></a>
							<a data-role="outdent" href="javascript:void(0)"><i class="fa fa-outdent"></i></a>
							<a data-role="insertUnorderedList" href="javascript:void(0)"><i class="fa fa-list-ul"></i></a>
							<a data-role="insertOrderedList" href="javascript:void(0)"><i class="fa fa-list-ol"></i></a>
							<a data-role="h1" href="javascript:void(0)">h<sup>1</sup></a>
							<a data-role="h2" href="javascript:void(0)">h<sup>2</sup></a>
							<a data-role="p" href="javascript:void(0)">p</a>
							<a data-role="subscript" href="javascript:void(0)"><i class="fa fa-subscript"></i></a>
							<a data-role="superscript" href="javascript:void(0)"><i class="fa fa-superscript"></i></a>
						</div>
					</div>
					<div id="editor" contenteditable=""></div>
					<textarea id="output" style="width:100%;height:400px;display:none;" name="recenzja_"></textarea>
				</td>
			</tr>
			<tr><td colspan=2 style="text-align:center;"> <button class="button" name="zapiszocene">Zapisz recenzje</button> </td></tr>
		</table>
	</form>