<h1>Edytuj recenzję</h1>
<?php $this->getMessage(); ?>

<form method="post">
<center style="padding-bottom:60px;">
	<div style="float:left;width:30%;">
		<h3>Ocena:</h3>
		<select name="ocena">
			<option disabled>Wybierz ocenę</option>
			<?php for ($i = -5; $i <= 5; $i++): ?>
				<option value="<?php echo $i?>" <?php if ($recenzjaForm['ocena'] == $i): ?>selected="selected"<?php endif ?>><?php echo $i ?></option>
			<?php endfor ?>
		</select>
	</div>
	<div style="float:left;width:50%;">
		<h3>Treść recenzji</h3>
		<p>
			<div id="editControls">
				<div>
					<a data-role="undo" href="javascript:void(0)"><i class="fa fa-undo"></i></a>
					<a data-role="redo" href="javascript:void(0)"><i class="fa fa-repeat"></i></a>
					<a data-role="bold" href="javascript:void(0)"><i class="fa fa-bold"></i></a>
					<a data-role="italic" href="javascript:void(0)"><i class="fa fa-italic"></i></a>
					<a data-role="underline" href="javascript:void(0)"><i class="fa fa-underline"></i></a>
					<a data-role="strikeThrough" href="javascript:void(0)"><i class="fa fa-strikethrough"></i></a>
					<a data-role="justifyLeft" href="javascript:void(0)"><i class="fa fa-align-left"></i></a>
					<a data-role="justifyCenter" href="javascript:void(0)"><i class="fa fa-align-center"></i></a>
					<a data-role="justifyRight" href="javascript:void(0)"><i class="fa fa-align-right"></i></a>
					<a data-role="justifyFull" href="javascript:void(0)"><i class="fa fa-align-justify"></i></a>
					<a data-role="indent" href="javascript:void(0)"><i class="fa fa-indent"></i></a>
					<a data-role="outdent" href="javascript:void(0)"><i class="fa fa-outdent"></i></a>
					<a data-role="insertUnorderedList" href="javascript:void(0)"><i class="fa fa-list-ul"></i></a>
					<a data-role="insertOrderedList" href="javascript:void(0)"><i class="fa fa-list-ol"></i></a>
					<a data-role="h1" href="javascript:void(0)">h<sup>1</sup></a>
					<a data-role="h2" href="javascript:void(0)">h<sup>2</sup></a>
					<a data-role="p" href="javascript:void(0)">p</a>
					<a data-role="subscript" href="javascript:void(0)"><i class="fa fa-subscript"></i></a>
					<a data-role="superscript" href="javascript:void(0)"><i class="fa fa-superscript"></i></a>
				</div>
			</div>
			<div id="editor" contenteditable=""><?php echo $recenzjaForm['tresc'] ?></div>
			<textarea id="output" name="tresc" style="width:100%;height:400px;display:none;"><?php echo $recenzjaForm['tresc'] ?></textarea>
		</p>
	</div>
	<div style="clear:both;">
	<br>
	Publikuj
	<input type="hidden" name="publikuj" value="0" />
	<input type="checkbox" name="publikuj" value="1" <?php if (!empty($recenzjaForm['publikuj'])): ?>checked="checked"<?php endif ?> />
	<br><br>
	<input class="button" type="submit" name="submit" value="Zatwierdź zmiany" />
</center>
</form>