<?php $this->getMessage(); ?>
<h2 style="text-align:center">	
	<form action="index.php?con=szukaj" method="post">
	<input type="text"  STYLE="width:200px; height: 20px" name="szukane">
	<button name="szukaj" STYLE="width:90px; height:30px">Szukaj</button><br><br>
	</form></h2>


<?php if($_POST['szukane']!="") {?><h3>Wyświetlanie wyników dla: '<?php echo $_POST['szukane'] ?>'. Znaleziono: <?php echo $znalezionych ?>. </h3>

<table style="text-align:left; margin-left:auto; margin-right:auto" border="1" >
	<thead style="text-align:center">
		<th width="50">Nr</th>
		<th width="400">Nazwa konferencji</th>
		<th width="200">Organizator</th>
		<th width="150">Miejsce</th>
		<th width="150">Data</th>
	</thead>
	<tbody>

	<?php $numer=0;?>
	<?php foreach ($result as $szukaj): ?>
							<?php// $result[$numer][0] to ID_konferencja?>
		<tr onMouseover="this.bgColor='#33CCFF'"onMouseout="this.bgColor='#FFFFFF'" class="odnosnik" style="cursor:pointer;" onClick="location.href='index.php'">
			<td style="text-align:center"><?php echo $numer+1; ?>.</td>
			<td><?php echo $result[$numer][1] ?></td>
			<td><?php echo $result[$numer][2] ?> <?php echo $result[$numer][3] ?></td>
			<td><?php echo $result[$numer][4] ?></td>
			<td><?php echo $result[$numer][5] ?></td>
		<?php $numer=numer+1;?>
		</tr>
		<?php endforeach ?>
		
		
	</tbody>
</table>
<?php } ?>

