<center><h1>Wyniki wyszukiwania: </h1></center>

<?php $this->getMessage(); ?>
		
		


	<form method="post" id ="formularz">
	</form>
		<table> 
	<?php
	
	echo "<p>";
 echo "<table boder=\"1\"><tr>";
 echo "<td bgcolor=\"#CC3399\"><strong>Nazwa konferencji:</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Data</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Miejsce</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Limit miejsc</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Program</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Termin zgłoszeń</strong></td>";
 echo "<td bgcolor=\"#CC3399\"><strong>Koszt</strong></td>";
 echo "</tr>";
	
 
while (  $row=mysql_fetch_row($wynik) ) {
    echo "</tr>";
	
	echo "<td bgcolor=\"#99ff00\">" . $row[1] . "</td>";
    echo "<td bgcolor=\"#ccff99\">" . $row[2] . "</td>";
    echo "<td bgcolor=\"#ccff99\">" . $row[3] . "</td>";
	echo "<td bgcolor=\"#ccff99\">" . $row[4] . "</td>";
	echo "<td bgcolor=\"#ccff99\">" . $row[5] . "</td>";
	echo "<td bgcolor=\"#ccff99\">" . $row[6] . "</td>";
	echo "<td bgcolor=\"#ccff99\">" . $row[7] . "</td>";

   echo "</tr>";
 }
 echo "</table>"; ?>
</table>
