<?php $this->getMessage(); ?>
<center><h2 style="margin:30px 0px 0px 20px;">Zarządzanie artykułami</h2></center>
<?php $this->getMessage(); 
global $selected_val;
$selected_val=0;?>
<div class="post entry" style="width:100%; margin:30px 0px 20px 0px;">
		<div class="hexagon"><a href="#"><i class="fa fa-book"></i></a></div>
		<div class="post-image">
			<figure>
				<div class="imgcon full">
				</div>
			</figure>
		</div>
    		<center><h2 style="margin:30px 0px 0px 20px;">Lista artykułów</h2>
			<form action="#" method="post">
			<select name="decision">
			
			<?php 
				$a=0;
				foreach($this->zarz_artykulami as $artykul)
				{
					echo "<option ";
					if ($a==0)
					echo "selected ";
					echo "value ='";
					echo $a;
					echo "'>";	
					echo $artykul['Tytul'];
					$a++;
				}	
			?>
			</select>
			<input type='submit' name='submit' value = "Wybierz"/>
	
			<h2>O atrykule :</h2> 
			<div class="border"></div>
			<p>
				<table style="width:460px;">
				<?php 
				if(isset($_POST['submit'])){
				$selected_val= $_POST['decision'];
			
				}
				?>
				<tr><td><b>Dotyczy konferencji :</b></td><td><b><?php echo $this->zarz_artykulami[$selected_val]['Nazwa'];?></b></tr>
				<tr><td><b>Autor: </b></td><td><b><?php echo $this->zarz_artykulami[$selected_val]['Imie']; echo " "; echo $this->zarz_artykulami[$selected_val]['Nazwisko']; ?> </b></td></tr>
				<tr><td><b>Tytuł: </b></td><td><b><?php echo $this->zarz_artykulami[$selected_val]['Tytul']; ?></b></td></tr>
				<tr><td><b>Treść: </b></td><td><b><?php echo  $this->zarz_artykulami[$selected_val]['Tresc']; ?></b></td></tr>
				<tr><td><b>Data Utworzenia: </b></td><td><b><?php  echo  $this->zarz_artykulami[$selected_val]['Data_Utworzenia']; ?></b></td></tr>
				<tr><td><b>Atrykuł </b></td><td><b>
				<?php if ($this->zarz_artykulami[$selected_val]['Opublikowany'] == '1')
				{
					echo "został opublikowany <tr>";
					echo "<center><INPUT TYPE = 'Submit' Name = 'Submit1' VALUE = 'Ukryj'></center> </tr>";
				}			
				else
				{
					echo "nie został jeszcze opublikowany<tr>";
					echo "<center><INPUT TYPE = 'Submit' Name = 'Submit2' VALUE = 'Opublikuj'></center> </tr>";	
				}
				?>
				</b></td></tr>
				</table>
			</p>


			</form></center>


	
		</div>
		<?php 
			if(isset($_POST['Submit1'])){
				mysql_query("UPDATE artykul SET Opublikowany = 0 WHERE ID_Artykul = '".addslashes($this->zarz_artykulami[$selected_val]['ID_Artykul'])."'") or die(mysql_error());
				$this->redirect("index.php?con=zarz_artykulami", "success", "Wybrany artykuł został  ukryty");
			}
			if(isset($_POST['Submit2'])){
				mysql_query("UPDATE artykul SET Opublikowany = 1 WHERE ID_Artykul = '".addslashes($this->zarz_artykulami[$selected_val]['ID_Artykul'])."'") or die(mysql_error());
				$this->redirect("index.php?con=zarz_artykulami", "success", "Wybrany artykuł został  opublikowany");
			}
			?>
