<h1>Zmien haslo</h1>

<?php $this->getMessage(); ?>

	<form method="post">
		<table> 
		<tr><td> Podaj swoje stare hasło </td><td> <input type="password" name="haslo"></td></tr>
		<tr><td> Podaj nowe hasło </td><td> <input type="password" name="nowehaslo"></td></tr>
		<tr><td> Podaj jeszcze raz nowe hasło </td><td> <input type="password" name="nowehaslo1"></td></tr>
		<tr><td colspan=2 style="text-align:center;"> <button name="akceptuj">Zapisz zmiany</button> </td></tr>
		</table>
	</form>